/* Mercado Euforia — 상품 데이터.
   관리자 대쉬보드에서 내보냈습니다: 2026-08-29
   이 파일을 assets 폴더에 덮어쓰고 배포하면 손님 화면에 반영됩니다. */
window.BRANDS = [
  {"id":"finca-hostalets","name":"Finca Hostalets","hall":"es","loc":"Barcelona, ES","since":1898,"h":38,"story":{"ko":"1898년부터 이어 온 카사 세우마의 브랜드. 올리브 재배자 호세 세우마가 만듭니다.","es":"Marca de Casa Seuma desde 1898. Elaborado por José Seuma, olivicultor.","en":"A Casa Seuma label since 1898, made by José Seuma, olive grower.","fr":"Marque de Casa Seuma depuis 1898, élaborée par José Seuma, oléiculteur.","de":"Eine Marke von Casa Seuma seit 1898, hergestellt von José Seuma, Olivenbauer.","it":"Marchio di Casa Seuma dal 1898, prodotto da José Seuma, olivicoltore.","zh":"卡萨塞乌马自1898年的品牌，由橄榄种植者何塞·塞乌马酿造。"}},
  {"id":"casa-olivar","name":"Casa Olivar","hall":"es","loc":"Jaén, ES","since":1968,"h":32,"story":{"ko":"3대째 하엔의 올리브밭을 지켜 온 가족 농장입니다.","es":"Finca familiar en Jaén, tercera generación de olivareros.","en":"A family grove in Jaén, third generation of olive growers.","fr":"Domaine familial à Jaén, troisième génération.","de":"Familienhain in Jaén, dritte Generation Olivenbauern.","it":"Azienda familiare a Jaén, terza generazione.","zh":"哈恩的家族橄榄园，已传承三代。"}},
  {"id":"dehesa-real","name":"Dehesa Real","hall":"es","loc":"Salamanca, ES","since":1954,"h":20,"story":{"ko":"살라망카 참나무 숲에서 도토리만 먹여 키웁니다.","es":"Cerdos criados en la dehesa salmantina, solo con bellota.","en":"Pigs raised on Salamanca oak pasture, acorn-fed only.","fr":"Porcs élevés dans la dehesa de Salamanque, au gland.","de":"Schweine aus der Eichenweide bei Salamanca, Eichelmast.","it":"Maiali allevati nella dehesa di Salamanca, solo a ghianda.","zh":"萨拉曼卡橡树牧场放养，只食橡果。"}},
  {"id":"bodega-aurora","name":"Bodega Aurora","hall":"es","loc":"Rioja Alta, ES","since":1901,"h":344,"story":{"ko":"리오하 알타의 1901년 지하 저장고에서 숙성합니다.","es":"Crianza en las bodegas subterráneas de 1901.","en":"Aged in the 1901 underground cellars of Rioja Alta.","fr":"Élevage dans les caves souterraines de 1901.","de":"Reifung in den Kellern von 1901 in der Rioja Alta.","it":"Affinamento nelle cantine sotterranee del 1901.","zh":"在里奥哈上区1901年的地下酒窖陈酿。"}},
  {"id":"taller-azul","name":"Taller Azul","hall":"es","loc":"Sevilla, ES","since":1987,"h":218,"story":{"ko":"세비야 구시가의 작은 공방. 전부 손으로 만듭니다.","es":"Pequeño taller en el casco antiguo de Sevilla. Todo a mano.","en":"A small workshop in old Seville. Everything by hand.","fr":"Petit atelier dans le vieux Séville. Tout à la main.","de":"Kleine Werkstatt in der Altstadt von Sevilla. Alles Handarbeit.","it":"Piccola bottega nel centro storico di Siviglia. Tutto a mano.","zh":"塞维利亚老城的小工坊，全手工制作。"}},
  {"id":"jeju-damda","name":"Jeju Damda","hall":"kr","loc":"Jeju, KR","since":2003,"h":168,"story":{"ko":"제주와 남해의 재료만 씁니다. 첨가물 없음.","es":"Solo ingredientes de Jeju y la costa sur. Sin aditivos.","en":"Only ingredients from Jeju and the south coast. No additives.","fr":"Uniquement des produits de Jeju et du sud. Sans additifs.","de":"Nur Zutaten von Jeju und der Südküste. Ohne Zusätze.","it":"Solo ingredienti di Jeju e della costa sud. Senza additivi.","zh":"只用济州与南海岸的原料，不添加。"}},
  {"id":"goun-son","name":"Goun Son","hall":"kr","loc":"Seoul, KR","since":1979,"h":288,"story":{"ko":"무형문화재 공방에서 이어 온 나전과 옻칠.","es":"Nácar y laca ottchil de un taller declarado patrimonio.","en":"Mother-of-pearl and ottchil lacquer from a heritage workshop.","fr":"Nacre et laque ottchil d’un atelier classé patrimoine.","de":"Perlmutt und Ottchil-Lack aus einer Kulturerbe-Werkstatt.","it":"Madreperla e lacca ottchil da una bottega patrimonio.","zh":"源自非物质文化遗产工坊的螺钿与大漆。"}},
  {"id":"hangyeol","name":"Hangyeol Beauty","hall":"kr","loc":"Seoul, KR","since":2011,"h":8,"story":{"ko":"한방 원료를 현대적으로 배합하는 서울의 브랜드.","es":"Marca de Seúl que reformula la herbología coreana.","en":"A Seoul brand reworking Korean herbal medicine.","fr":"Marque séoulite qui réinvente l’herboristerie coréenne.","de":"Seouler Marke, die koreanische Kräuterkunde neu denkt.","it":"Marchio di Seoul che rilegge l’erboristeria coreana.","zh":"首尔品牌，以现代方式调配韩方原料。"}},
];

window.PRODUCTS = [
  {"id":35,"hall":"es","cat":"food","brand":"finca-hostalets","eur":63,"g":"500ml","stock":100,"badge":"new","name":{"ko":"유기농 엑스트라 버진 올리브 오일","es":"Aceite de oliva virgen extra ecológico","en":"유기농 엑스트라 버진 올리브 오일","fr":"Huile d'olive extra vierge bio","de":"Bio natives Olivenöl extra","it":"Olio extra vergine di oliva","zh":"有机特级初榨橄榄油"},"tag":{"ko":"Arbequina del Priorat – Family Reserve – 500 ml","es":"Arbequina del Priorat – Reserva Familiar – 500 ml","en":"Arbequina del Priorat – Family Reserve – 500 ml","fr":"Arbequina del Priorat – Réserve Familiale – 500 ml","de":"Arbequina del Priorat – Family Reserve – 500 ml","it":"Arbequina del Priorat – Riserva Familiare – 500 ml","zh":"Arbequina del Priorat –家庭储备– 500毫升"},"desc":{"ko":"과일향이 풍부하고 섬세하면서도 입안 가득 풍성한 맛을 선사합니다.\n에메랄드빛 녹색을 띠며, 토마토, 아티초크, 펜넬 등의 채소 향과 은은한 그린 아몬드 향이 어우러진 강렬한 과일향을 자랑합니다. 입안에서는 떫은맛 없이 신선하며, 살짝 매콤한 여운이 감돌아 코끝의 섬세함과 입안에서의 풍성함을 동시에 느낄 수 있습니다.","es":"Afrutado, delicado y delicioso. Es de color verde esmeralda y tiene un intenso aroma afrutado con notas de verduras como tomates, alcachofas, hinojo y sutiles almendras verdes. En boca, es fresco sin sabor ligero, y se puede sentir la delicadeza de la punta de la nariz y la riqueza en boca al mismo tiempo.","en":"과일향이 풍부하고 섬세하면서도 입안 가득 풍성한 맛을 선사합니다.\n에메랄드빛 녹색을 띠며, 토마토, 아티초크, 펜넬 등의 채소 향과 은은한 그린 아몬드 향이 어우러진 강렬한 과일향을 자랑합니다. 입안에서는 떫은맛 없이 신선하며, 살짝 매콤한 여운이 감돌아 코끝의 섬세함과 입안에서의 풍성함을 동시에 느낄 수 있습니다.","fr":"Fruité, délicat et appétissant. Il est vert émeraude et a un arôme fruité intense avec des notes de légumes comme les tomates, les artichauts, le fenouil et les amandes vertes subtiles. En bouche, il est frais sans goût léger, et vous pouvez sentir la délicatesse du bout du nez et la richesse de la bouche en même temps.","de":"Fruchtig, zart und köstlich. Es ist smaragdgrün und hat ein intensives fruchtiges Aroma mit Noten von Gemüse wie Tomaten, Artischocken, Fenchel und dezenten grünen Mandeln. Im Mund ist es frisch ohne leichten Geschmack, und man spürt gleichzeitig die Zartheit der Nasenspitze und den Reichtum im Mund.","it":"Fruttato, delicato e appetitoso. È verde smeraldo e ha un profumo fruttato intenso con note di verdure come pomodori, carciofi, finocchi e sottili mandorle verdi. In bocca è fresco senza sapore leggero, e si può sentire la delicatezza della punta del naso e la ricchezza in bocca allo stesso tempo.","zh":"果味浓郁、细腻、令人垂涎三尺。它呈翡翠绿色，果香浓郁，散发着西红柿、朝鲜蓟、茴香和微妙的绿杏仁等蔬菜的香气。在口中，它清新而没有淡淡的味道，您可以同时感受到鼻尖的美味和口中的丰富。"}},
];

/* 환율: 하나은행 매매기준율을 하루 한 번 받아 넣는 값 + 판매 버퍼 */
window.FX = { base: 1614.2, buffer: 0.03, at: "2026-08-27 09:00", source: "하나은행 매매기준율" };
window.FX.rate = Math.round(window.FX.base * (1 + window.FX.buffer) * 10) / 10;
